create table games (
    id integer generated by default as identity,
    name varchar(155) not null unique,
    description varchar(500),
    release_year integer check ( release_year >= 1950 ),
    primary key (id)
);